/**
 * Render the full contract index as a Markdown registry. One section
 * per kind, one subsection per entity. Used by `act --markdown` for
 * pipe-friendly output that diffs cleanly between branches.
 *
 * Output is plain ASCII (no ANSI escapes) regardless of `picocolors`
 * settings — readers expect Markdown to be paste-able into a PR body
 * or a static doc file.
 */
import type { DomainModel } from "../client/types/index.js";
import {
  type ContractIndex,
  eventStatus,
  listByKind,
} from "./contract-index.js";

const loc = (file?: string, line?: number): string => {
  if (!file) return "";
  return line ? `${file}:${line}` : file;
};

const findActionsEmitting = (
  model: DomainModel,
  eventName: string
): Array<{ state: string; action: string; file?: string; line?: number }> => {
  const out: Array<{
    state: string;
    action: string;
    file?: string;
    line?: number;
  }> = [];
  for (const st of model.states) {
    for (const act of st.actions) {
      if (act.emits.includes(eventName)) {
        out.push({
          state: st.name,
          action: act.name,
          file: st.file,
          line: act.line,
        });
      }
    }
  }
  return out;
};

const findReactionsFor = (
  model: DomainModel,
  eventName: string
): Array<{
  slice?: string;
  handler: string;
  dispatches: string[];
  file?: string;
  line?: number;
}> => {
  const out: Array<{
    slice?: string;
    handler: string;
    dispatches: string[];
    file?: string;
    line?: number;
  }> = [];
  for (const sl of model.slices) {
    for (const r of sl.reactions) {
      if (r.event === eventName) {
        out.push({
          slice: sl.name,
          handler: r.handlerName,
          dispatches: r.dispatches,
          file: r.file ?? sl.file,
          line: r.line,
        });
      }
    }
  }
  for (const r of model.reactions) {
    if (r.event === eventName) {
      out.push({
        handler: r.handlerName,
        dispatches: r.dispatches,
        file: r.file,
        line: r.line,
      });
    }
  }
  return out;
};

const findProjectionsFor = (
  model: DomainModel,
  eventName: string
): Array<{ name: string; file?: string }> =>
  model.projections
    .filter((p) => p.handles.includes(eventName))
    .map((p) => ({ name: p.name, file: p.file }));

const fileSuffix = (file?: string, line?: number): string => {
  const l = loc(file, line);
  return l ? `  *(${l})*` : "";
};

/** Render a captured Zod expression. Single-line goes inline with
 *  backticks; multi-line gets a fenced code block so newlines survive. */
const renderSchema = (s: string | undefined): string => {
  if (!s) return "_(not captured)_";
  if (!s.includes("\n")) return `\`${s}\``;
  const indented = s
    .split("\n")
    .map((l) => `  ${l}`)
    .join("\n");
  return `\n\n  \`\`\`ts\n${indented}\n  \`\`\``;
};

export function formatMarkdown(idx: ContractIndex): string {
  const m = idx.model;
  const lines: string[] = [];

  lines.push("# Act Contracts Registry");
  lines.push("");
  lines.push(
    `_Generated by \`act --markdown\`. ${m.states.length} states, ${m.slices.length} slices, ${m.projections.length} projections, ${idx.allEventNames.size} events._`
  );
  lines.push("");

  // ── Events ──────────────────────────────────────────────────────────
  lines.push("## Events");
  lines.push("");
  const events = listByKind(idx, "event");
  if (events.length === 0) lines.push("_(none)_\n");
  for (const e of events) {
    let schema: string | undefined;
    let owningState: string | undefined;
    for (const st of m.states) {
      const ev = st.events.find((x) => x.name === e.name);
      if (ev) {
        schema = ev.schema;
        owningState = st.name;
        break;
      }
    }
    const status = eventStatus(e.name, idx.allEventNames);
    const statusLabel =
      status.status === "active"
        ? "active"
        : `deprecated — superseded by **${status.supersededBy}**`;
    lines.push(`### \`${e.name}\``);
    // `e.file` always carries the state's source file via buildContractIndex.
    if (e.file) lines.push(`- **defined in:** \`${loc(e.file, e.line)}\``);
    if (owningState && owningState !== e.name)
      lines.push(`- **on state:** \`${owningState}\``);
    lines.push(`- **schema:** ${renderSchema(schema)}`);
    lines.push(`- **status:** ${statusLabel}`);

    const producers = findActionsEmitting(m, e.name);
    if (producers.length > 0) {
      lines.push("- **producers:**");
      for (const p of producers)
        lines.push(
          `  - \`${p.action}\` (state \`${p.state}\`)${fileSuffix(p.file, p.line)}`
        );
    } else {
      lines.push("- **producers:** _(none)_");
    }
    const reactions = findReactionsFor(m, e.name);
    const projections = findProjectionsFor(m, e.name);
    if (reactions.length === 0 && projections.length === 0) {
      lines.push("- **consumers:** _(none)_");
    } else {
      lines.push("- **consumers:**");
      for (const r of reactions) {
        const slice = r.slice ? `\`${r.slice}\`::` : "";
        const triggers =
          r.dispatches.length > 0
            ? ` → triggers ${r.dispatches.map((d) => `\`${d}\``).join(", ")}`
            : "";
        lines.push(
          `  - reaction ${slice}\`${r.handler}\`${triggers}${fileSuffix(r.file, r.line)}`
        );
      }
      for (const p of projections)
        lines.push(`  - projection \`${p.name}\`${fileSuffix(p.file)}`);
    }
    lines.push("");
  }

  // ── Actions ─────────────────────────────────────────────────────────
  lines.push("## Actions");
  lines.push("");
  const actions = listByKind(idx, "action");
  if (actions.length === 0) lines.push("_(none)_\n");
  for (const a of actions) {
    let action:
      | { name: string; emits: string[]; invariants: string[]; line?: number }
      | undefined;
    let stateFile: string | undefined;
    for (const st of m.states) {
      if (a.qualifier && st.name !== a.qualifier) continue;
      const found = st.actions.find((x) => x.name === a.name);
      if (found) {
        action = found;
        stateFile = st.file;
        break;
      }
    }
    lines.push(`### \`${a.name}\``);
    if (a.qualifier) lines.push(`- **on state:** \`${a.qualifier}\``);
    if (stateFile)
      lines.push(
        `- **defined in:** \`${loc(stateFile, action?.line ?? a.line)}\``
      );
    if (action) {
      if (action.invariants.length > 0) {
        lines.push("- **invariants:**");
        for (const inv of action.invariants) lines.push(`  - ${inv}`);
      }
      if (action.emits.length > 0) {
        lines.push("- **emits:**");
        for (const ev of action.emits) lines.push(`  - \`${ev}\``);
      } else {
        lines.push("- **emits:** _(none)_");
      }
    }
    lines.push("");
  }

  // ── States ──────────────────────────────────────────────────────────
  lines.push("## States");
  lines.push("");
  const states = listByKind(idx, "state");
  if (states.length === 0) lines.push("_(none)_\n");
  for (const s of states) {
    const st = m.states.find((x) => x.name === s.name);
    lines.push(`### \`${s.name}\``);
    if (s.file) lines.push(`- **defined in:** \`${loc(s.file, s.line)}\``);
    if (st) {
      if (st.actions.length > 0)
        lines.push(
          `- **actions:** ${st.actions.map((x) => `\`${x.name}\``).join(", ")}`
        );
      if (st.events.length > 0)
        lines.push(
          `- **events:** ${st.events.map((x) => `\`${x.name}\``).join(", ")}`
        );
    }
    lines.push("");
  }

  // ── Slices ──────────────────────────────────────────────────────────
  lines.push("## Slices");
  lines.push("");
  const slices = listByKind(idx, "slice");
  if (slices.length === 0) lines.push("_(none)_\n");
  for (const s of slices) {
    const sl = m.slices.find((x) => x.name === s.name);
    lines.push(`### \`${s.name}\``);
    if (s.file) lines.push(`- **defined in:** \`${loc(s.file, s.line)}\``);
    if (sl) {
      if (sl.error) lines.push(`- **error:** ${sl.error}`);
      if (sl.states.length > 0)
        lines.push(
          `- **states:** ${sl.states.map((x) => `\`${x}\``).join(", ")}`
        );
      if (sl.projections.length > 0)
        lines.push(
          `- **projections:** ${sl.projections.map((x) => `\`${x}\``).join(", ")}`
        );
      if (sl.reactions.length > 0) {
        lines.push("- **reactions:**");
        for (const r of sl.reactions) {
          const triggers =
            r.dispatches.length > 0
              ? ` → ${r.dispatches.map((d) => `\`${d}\``).join(", ")}`
              : "";
          lines.push(
            `  - \`${r.event}\` → \`${r.handlerName}\`${triggers}${fileSuffix(r.file, r.line)}`
          );
        }
      }
    }
    lines.push("");
  }

  // ── Projections ─────────────────────────────────────────────────────
  lines.push("## Projections");
  lines.push("");
  const projections = listByKind(idx, "projection");
  if (projections.length === 0) lines.push("_(none)_\n");
  for (const p of projections) {
    const pr = m.projections.find((x) => x.name === p.name);
    lines.push(`### \`${p.name}\``);
    if (pr?.file) lines.push(`- **defined in:** \`${loc(pr.file, pr.line)}\``);
    if (pr && pr.handles.length > 0)
      lines.push(
        `- **handles:** ${pr.handles.map((x) => `\`${x}\``).join(", ")}`
      );
    lines.push("");
  }

  // ── Reactions ───────────────────────────────────────────────────────
  lines.push("## Reactions");
  lines.push("");
  const reactions = listByKind(idx, "reaction");
  if (reactions.length === 0) lines.push("_(none)_\n");
  for (const r of reactions) {
    const [sliceName, eventName] = (r.qualifier ?? "::").split("::");
    lines.push(`### \`${r.name}\``);
    if (sliceName && sliceName !== "*")
      lines.push(`- **in slice:** \`${sliceName}\``);
    if (eventName) lines.push(`- **on event:** \`${eventName}\``);
    if (r.file) lines.push(`- **defined in:** \`${loc(r.file, r.line)}\``);
    const sliceReaction = m.slices
      .find((x) => x.name === sliceName)
      ?.reactions.find(
        (rr) => rr.handlerName === r.name && rr.event === eventName
      );
    const orchReaction = m.reactions.find(
      (rr) => rr.handlerName === r.name && rr.event === eventName
    );
    const inner = sliceReaction ?? orchReaction;
    if (inner && inner.dispatches.length > 0) {
      lines.push(
        `- **triggers:** ${inner.dispatches.map((d) => `\`${d}\``).join(", ")}`
      );
    }
    lines.push("");
  }

  return lines.join("\n");
}
